const AppConstants = {
  TOAST_DURATION: 5000,
  TOAST_PADDING: 15,
  TOAST_POSITION: 60,
  TOAST_BORDER_RADIUS: 10,
  TOAST_BORDER_WIDTH: 1,
  TOAST_LEFT: 10,
  TOAST_RIGHT: 10,
  SHADOW_OFFSET_WIDTH: 0,
  SHADOW_OFFSET_HEIGHT: 4,
  SHADOW_OPACITY: 0.5,
  SHADOW_RADIUS: 4,
};

export default AppConstants;